/** LSP semantic token color map. */
export function getSemanticTokenColors(p) {
  const { purple, property, parameter, variable, fn, builtin, method, type, fg } = p;
  return {
    'namespace': type,
    'class': type,
    'enum': type,
    'interface': type,
    'struct': type,
    'typeParameter': type,
    'parameter': parameter,
    'variable': variable,
    'property': property,
    'enumMember': p.constant,
    'event': fn,
    'function': fn,
    'method': method,
    'macro': builtin,
    'keyword': p.keyword,
    'modifier': p.storage,
    'comment': p.comment,
    'string': p.string,
    'number': p.constant,
    'regexp': p.regexp,
    'operator': p.operator,
    'decorator': fn,
    'type': type,
    'builtin': builtin,
    'selfParameter': purple,
    'class.declaration': type,
    'function.declaration': fn,
    'method.declaration': method,
    'property.declaration': property,
    'variable.declaration': variable,
    'parameter.declaration': parameter,
    'constant.builtin': purple,
    'function.builtin': builtin,
    'magicFunction': fn,
    'property:python': fg,
    'variable:python': fg,
    'component': builtin,
  };
}
