import { mix, muted, withAlpha } from '../color-utils.mjs';

/** Editor internals: diagnostics, brackets, sticky scroll, ghost text, rulers. */
export function getEditorColors(p) {
  const { isDark, fg, bg, surface, editor, border, mutedFg, primary, error, warning, success, info, selection, selectionHi, brackets, stickyScroll, ghostText, type, parameter } = p;

  return {
    'editor.background': editor,
    'editor.foreground': fg,
    'editorLineNumber.foreground': mutedFg,
    'editorLineNumber.activeForeground': muted(fg, bg, 0.78),
    'editorCursor.foreground': primary,
    'editor.selectionBackground': selection,
    'editor.inactiveSelectionBackground': selectionHi,
    'editor.selectionHighlightBackground': selectionHi,
    'editor.wordHighlightBackground': withAlpha(muted(fg, bg, 0.5), 0.35),
    'editor.wordHighlightStrongBackground': withAlpha(primary, 0.2),
    'editor.findMatchBackground': withAlpha(primary, 0.4),
    'editor.findMatchHighlightBackground': withAlpha(primary, 0.2),
    'editor.findRangeHighlightBackground': withAlpha(warning, 0.18),
    'editor.hoverHighlightBackground': isDark ? mix(editor, '#FFFFFF', 0.06) : mix(editor, '#000000', 0.04),
    'editor.lineHighlightBackground': isDark ? mix(editor, '#FFFFFF', 0.04) : mix(editor, '#000000', 0.03),
    'editor.lineHighlightBorder': '#00000000',
    'editorIndentGuide.background1': border,
    'editorIndentGuide.activeBackground1': muted(border, fg, 0.5),
    'editorWhitespace.foreground': withAlpha(mutedFg, 0.5),
    'editorBracketMatch.background': withAlpha(primary, 0.2),
    'editorBracketMatch.border': primary,
    'editorBracketHighlight.foreground1': brackets[0],
    'editorBracketHighlight.foreground2': brackets[1],
    'editorBracketHighlight.foreground3': brackets[2],
    'editorBracketHighlight.foreground4': brackets[3],
    'editorBracketHighlight.foreground5': brackets[4],
    'editorBracketHighlight.foreground6': brackets[5],
    'editorBracketHighlight.unexpectedBracket.foreground': error,
    'editorOverviewRuler.border': border,
    'editorOverviewRuler.findMatchForeground': withAlpha(primary, 0.8),
    'editorOverviewRuler.rangeHighlightForeground': withAlpha(warning, 0.7),
    'editorOverviewRuler.selectionHighlightForeground': withAlpha(primary, 0.6),
    'editorOverviewRuler.wordHighlightForeground': withAlpha(info, 0.6),
    'editorOverviewRuler.wordHighlightStrongForeground': withAlpha(info, 0.8),
    'editorOverviewRuler.modifiedForeground': info,
    'editorOverviewRuler.addedForeground': success,
    'editorOverviewRuler.deletedForeground': error,
    'editorOverviewRuler.errorForeground': error,
    'editorOverviewRuler.warningForeground': warning,
    'editorOverviewRuler.infoForeground': primary,
    'editorGutter.background': editor,
    'editorGutter.modifiedBackground': info,
    'editorGutter.addedBackground': success,
    'editorGutter.deletedBackground': error,
    'editorWidget.background': surface,
    'editorWidget.border': border,
    'editorSuggestWidget.background': surface,
    'editorSuggestWidget.border': border,
    'editorSuggestWidget.foreground': fg,
    'editorSuggestWidget.selectedBackground': withAlpha(primary, isDark ? 0.22 : 0.14),
    'editorSuggestWidget.highlightForeground': primary,
    'editorHoverWidget.background': surface,
    'editorHoverWidget.border': border,
    'editorError.foreground': error,
    'editorWarning.foreground': warning,
    'editorInfo.foreground': info,
    'editorHint.foreground': mutedFg,
    'editorRuler.foreground': withAlpha(border, 0.8),
    'editorCodeLens.foreground': mutedFg,
    'editorLink.activeForeground': primary,
    'editorGhostText.foreground': ghostText,
    'editorGhostText.background': withAlpha(editor, 0.01),
    'editorInlayHint.foreground': mutedFg,
    'editorInlayHint.background': withAlpha(surface, isDark ? 0.55 : 0.75),
    'editorInlayHint.typeForeground': type,
    'editorInlayHint.parameterForeground': parameter,
    'editorStickyScroll.background': stickyScroll,
    'editorStickyScrollHover.background': isDark ? mix(stickyScroll, '#FFFFFF', 0.06) : mix(stickyScroll, '#000000', 0.04),
    'editorStickyScroll.shadow': isDark ? '#00000044' : '#00000018',

    'diffEditor.insertedTextBackground': withAlpha(success, 0.14),
    'diffEditor.removedTextBackground': withAlpha(error, 0.14),
    'diffEditor.insertedLineBackground': withAlpha(success, 0.1),
    'diffEditor.removedLineBackground': withAlpha(error, 0.1),

    'peekView.border': primary,
    'peekViewEditor.background': surface,
    'peekViewEditor.matchHighlightBackground': withAlpha(warning, 0.25),
    'peekViewResult.background': bg,
    'peekViewResult.selectionBackground': withAlpha(primary, isDark ? 0.22 : 0.14),
    'peekViewResult.matchHighlightBackground': withAlpha(warning, 0.2),
    'peekViewTitle.background': bg,
    'peekViewTitleLabel.foreground': fg,
    'peekViewTitleDescription.foreground': mutedFg,
  };
}
